// jobData.js

const jobs = [
  {
    id: "1",
    title: "Junior Frontend Developer",
    company: "Tech Corp",
    location: "New York, NY",
    salary: "$60,000 - $70,000",
    level: "Junior",
    description: "Join our team to develop modern web applications.",
    requirements: [
      "Proficiency in HTML, CSS, and JavaScript.",
      "Familiarity with React or Vue.js.",
      "Basic understanding of RESTful APIs.",
      "Strong problem-solving skills.",
      "Ability to work in a fast-paced environment.",
    ],
    responsibilities: [
      "Collaborate with the design team to implement UI designs.",
      "Develop and maintain web applications.",
      "Participate in code reviews and contribute to team best practices.",
      "Write unit and integration tests.",
    ],
    additionalInfo: "This position offers growth opportunities and mentorship.",
    companyWebsite: "https://techcorp.com",
    benefits: [
      "Health, dental, and vision insurance.",
      "401(k) matching.",
      "Paid time off and holidays.",
      "Remote work options.",
    ],
    applicationDeadline: "2024-12-01",
    workHours: "Full-time, 40 hours per week.",
    jobType: "Permanent",
    remoteOptions: true,
    tags: ["JavaScript", "React", "Frontend"],
  },
  {
    id: "2",
    title: "Mobile App Developer",
    company: "Innovate LLC",
    location: "San Francisco, CA",
    salary: "$80,000 - $90,000",
    level: "Mid-Level",
    description: "Work on innovative mobile solutions.",
    requirements: [
      "Experience with React Native or Flutter.",
      "Strong knowledge of mobile app development lifecycle.",
      "Familiarity with both iOS and Android platforms.",
      "Understanding of Agile methodologies.",
    ],
    responsibilities: [
      "Design and build advanced applications for mobile.",
      "Collaborate with cross-functional teams to define, design, and ship new features.",
      "Unit-test code for robustness, including edge cases.",
      "Maintain code quality and organization.",
    ],
    additionalInfo: "Remote work options available.",
    companyWebsite: "https://innovate.com",
    benefits: [
      "Flexible working hours.",
      "Health insurance and wellness programs.",
      "Professional development opportunities.",
    ],
    applicationDeadline: "2024-11-15",
    workHours: "Full-time, 40 hours per week.",
    jobType: "Permanent",
    remoteOptions: true,
    tags: ["React Native", "Mobile Development"],
  },
  {
    id: "3",
    title: "Senior Backend Developer",
    company: "Data Solutions",
    location: "Austin, TX",
    salary: "$110,000 - $130,000",
    level: "Senior",
    description: "Lead backend development efforts for our products.",
    requirements: [
      "Strong experience with Node.js and Express.",
      "Knowledge of database systems like PostgreSQL and MongoDB.",
      "Experience with cloud services (AWS, Azure).",
      "Strong understanding of software development best practices.",
      "Excellent troubleshooting and debugging skills.",
    ],
    responsibilities: [
      "Develop and maintain server-side applications.",
      "Integrate user-facing elements with server-side logic.",
      "Ensure performance, quality, and responsiveness of applications.",
      "Collaborate with frontend developers on API design.",
    ],
    additionalInfo: "Flexible working hours and remote work options.",
    companyWebsite: "https://datasolutions.com",
    benefits: [
      "Comprehensive health insurance.",
      "401(k) retirement plan.",
      "Paid sick leave and vacation time.",
    ],
    applicationDeadline: "2024-10-30",
    workHours: "Full-time, 40 hours per week.",
    jobType: "Permanent",
    remoteOptions: false,
    tags: ["Node.js", "Backend", "AWS"],
  },
  {
    id: "4",
    title: "UI/UX Designer",
    company: "Creative Minds",
    location: "Los Angeles, CA",
    salary: "$70,000 - $85,000",
    level: "Mid-Level",
    description: "Design engaging user experiences across platforms.",
    requirements: [
      "Proficient in design tools (Sketch, Figma, Adobe XD).",
      "Strong portfolio demonstrating design skills.",
      "Understanding of user-centered design principles.",
      "Ability to conduct user testing and analyze results.",
    ],
    responsibilities: [
      "Conduct user research and evaluate user feedback.",
      "Create wireframes, prototypes, and user flows.",
      "Collaborate with developers to ensure design feasibility.",
      "Present design concepts to stakeholders.",
    ],
    additionalInfo: "Team-building activities and workshops available.",
    companyWebsite: "https://creativeminds.com",
    benefits: [
      "Health and wellness programs.",
      "Paid time off and flexible scheduling.",
      "Opportunities for professional growth.",
    ],
    applicationDeadline: "2024-11-30",
    workHours: "Full-time, 40 hours per week.",
    jobType: "Permanent",
    remoteOptions: true,
    tags: ["UI Design", "UX Design"],
  },
  {
    id: "5",
    title: "Full Stack Developer",
    company: "NextGen Tech",
    location: "Chicago, IL",
    salary: "$90,000 - $110,000",
    level: "Mid-Level",
    description: "Develop full-stack applications for diverse clients.",
    requirements: [
      "Experience with front-end frameworks (React, Angular).",
      "Knowledge of backend frameworks (Node.js, Django).",
      "Understanding of version control (Git).",
      "Ability to manage multiple projects simultaneously.",
    ],
    responsibilities: [
      "Design and develop scalable applications.",
      "Write clean, maintainable code.",
      "Collaborate with cross-functional teams to deliver solutions.",
      "Provide technical support and troubleshooting.",
    ],
    additionalInfo: "Opportunities for skill development and certifications.",
    companyWebsite: "https://nextgentech.com",
    benefits: [
      "Health insurance coverage.",
      "Paid vacation and holidays.",
      "Training and certification reimbursement.",
    ],
    applicationDeadline: "2024-12-15",
    workHours: "Full-time, 40 hours per week.",
    jobType: "Permanent",
    remoteOptions: true,
    tags: ["Full Stack", "React", "Node.js"],
  },
  // Add more jobs as needed
  // 6 to 30 jobs can follow the same structure.
  {
    id: "6",
    title: "Data Scientist",
    company: "Analytics Co.",
    location: "Seattle, WA",
    salary: "$100,000 - $120,000",
    level: "Senior",
    description: "Analyze and interpret complex data sets.",
    requirements: [
      "Experience with Python and data analysis libraries (Pandas, NumPy).",
      "Knowledge of machine learning techniques.",
      "Strong statistical analysis skills.",
      "Ability to communicate data findings effectively.",
    ],
    responsibilities: [
      "Develop predictive models and algorithms.",
      "Visualize data insights for stakeholders.",
      "Collaborate with engineers to integrate models into applications.",
      "Conduct experiments and A/B testing.",
    ],
    additionalInfo: "Work with industry-leading data professionals.",
    companyWebsite: "https://analyticsco.com",
    benefits: [
      "Comprehensive health and dental insurance.",
      "401(k) retirement plan with matching.",
      "Flexible working hours.",
    ],
    applicationDeadline: "2024-11-10",
    workHours: "Full-time, 40 hours per week.",
    jobType: "Permanent",
    remoteOptions: true,
    tags: ["Data Science", "Python", "Machine Learning"],
  },
  {
    id: "7",
    title: "Product Manager",
    company: "Startup Hub",
    location: "Boston, MA",
    salary: "$95,000 - $115,000",
    level: "Senior",
    description: "Drive product strategy and execution.",
    requirements: [
      "Proven experience in product management.",
      "Strong analytical skills and data-driven mindset.",
      "Excellent communication and teamwork abilities.",
      "Ability to prioritize tasks effectively.",
    ],
    responsibilities: [
      "Define product vision and roadmap.",
      "Collaborate with engineering, design, and marketing teams.",
      "Conduct market research and analyze customer needs.",
      "Track product performance and iterate based on feedback.",
    ],
    additionalInfo: "Dynamic startup environment with equity options.",
    companyWebsite: "https://startuphq.com",
    benefits: [
      "Stock options and equity.",
      "Comprehensive health benefits.",
      "Flexible vacation policy.",
    ],
    applicationDeadline: "2024-10-25",
    workHours: "Full-time, 40 hours per week.",
    jobType: "Permanent",
    remoteOptions: true,
    tags: ["Product Management", "Agile", "Leadership"],
  },
  {
    id: "8",
    title: "DevOps Engineer",
    company: "Cloud Services",
    location: "Miami, FL",
    salary: "$90,000 - $110,000",
    level: "Mid-Level",
    description: "Automate and optimize CI/CD processes.",
    requirements: [
      "Experience with CI/CD tools (Jenkins, GitLab CI).",
      "Strong understanding of containerization (Docker, Kubernetes).",
      "Knowledge of cloud infrastructure (AWS, Azure).",
      "Strong scripting skills (Bash, Python).",
    ],
    responsibilities: [
      "Manage cloud infrastructure and deployment pipelines.",
      "Monitor system performance and optimize resources.",
      "Collaborate with development teams to implement best practices.",
      "Troubleshoot and resolve issues in production environments.",
    ],
    additionalInfo: "Flexible remote work and collaborative culture.",
    companyWebsite: "https://cloudservices.com",
    benefits: [
      "Health insurance and wellness programs.",
      "401(k) with company match.",
      "Training and professional development opportunities.",
    ],
    applicationDeadline: "2024-11-20",
    workHours: "Full-time, 40 hours per week.",
    jobType: "Permanent",
    remoteOptions: true,
    tags: ["DevOps", "AWS", "Automation"],
  },
  {
    id: "9",
    title: "Graphic Designer",
    company: "Design Studio",
    location: "Orlando, FL",
    salary: "$55,000 - $65,000",
    level: "Entry-Level",
    description: "Create visual content for various platforms.",
    requirements: [
      "Proficiency in Adobe Creative Suite.",
      "Strong portfolio showcasing design work.",
      "Ability to work collaboratively and take feedback.",
      "Basic understanding of web design principles.",
    ],
    responsibilities: [
      "Design graphics for websites, social media, and marketing materials.",
      "Assist in the development of brand guidelines.",
      "Collaborate with clients to understand their needs.",
      "Stay updated on design trends and tools.",
    ],
    additionalInfo: "Supportive team environment with growth potential.",
    companyWebsite: "https://designstudio.com",
    benefits: [
      "Health insurance.",
      "Flexible working hours.",
      "Paid time off.",
    ],
    applicationDeadline: "2024-10-30",
    workHours: "Full-time, 40 hours per week.",
    jobType: "Permanent",
    remoteOptions: false,
    tags: ["Graphic Design", "Adobe", "Creativity"],
  },
  {
    id: "10",
    title: "Cybersecurity Analyst",
    company: "Secure IT",
    location: "Washington, D.C.",
    salary: "$75,000 - $90,000",
    level: "Mid-Level",
    description: "Protect our systems and data from cyber threats.",
    requirements: [
      "Experience with security tools and technologies.",
      "Knowledge of networking concepts and protocols.",
      "Certifications like CISSP or CEH are a plus.",
      "Strong analytical and problem-solving skills.",
    ],
    responsibilities: [
      "Monitor network traffic for suspicious activities.",
      "Conduct security audits and vulnerability assessments.",
      "Develop and implement security policies and procedures.",
      "Collaborate with IT teams to enhance security measures.",
    ],
    additionalInfo: "Opportunities for further training and certifications.",
    companyWebsite: "https://secureit.com",
    benefits: [
      "Comprehensive health insurance.",
      "401(k) with employer match.",
      "Professional development opportunities.",
    ],
    applicationDeadline: "2024-11-05",
    workHours: "Full-time, 40 hours per week.",
    jobType: "Permanent",
    remoteOptions: true,
    tags: ["Cybersecurity", "Analyst", "Network Security"],
  },
  {
    id: "11",
    title: "Software Tester",
    company: "Quality Assurance Inc.",
    location: "Philadelphia, PA",
    salary: "$50,000 - $60,000",
    level: "Entry-Level",
    description: "Test software applications for quality assurance.",
    requirements: [
      "Familiarity with software testing methodologies.",
      "Basic understanding of programming languages is a plus.",
      "Strong attention to detail.",
      "Good communication skills.",
    ],
    responsibilities: [
      "Create and execute test plans and cases.",
      "Identify and document defects in software.",
      "Collaborate with developers to ensure quality.",
      "Participate in sprint planning and retrospectives.",
    ],
    additionalInfo: "Training provided for new hires.",
    companyWebsite: "https://qualityassurance.com",
    benefits: [
      "Health and dental insurance.",
      "Paid holidays and time off.",
      "Flexible work hours.",
    ],
    applicationDeadline: "2024-12-01",
    workHours: "Full-time, 40 hours per week.",
    jobType: "Permanent",
    remoteOptions: false,
    tags: ["Testing", "QA", "Software"],
  },
  {
    id: "12",
    title: "Content Writer",
    company: "Content Creators",
    location: "Remote",
    salary: "$45,000 - $55,000",
    level: "Entry-Level",
    description: "Write engaging content for blogs and websites.",
    requirements: [
      "Strong writing and editing skills.",
      "Familiarity with SEO best practices.",
      "Ability to conduct research on various topics.",
      "Experience with content management systems is a plus.",
    ],
    responsibilities: [
      "Create high-quality blog posts and articles.",
      "Collaborate with the marketing team to develop content strategies.",
      "Edit and proofread content before publication.",
      "Monitor content performance and make adjustments as needed.",
    ],
    additionalInfo: "Work from anywhere with flexible hours.",
    companyWebsite: "https://contentcreators.com",
    benefits: [
      "Remote work opportunities.",
      "Flexible scheduling.",
      "Professional development support.",
    ],
    applicationDeadline: "2024-10-20",
    workHours: "Part-time, 20 hours per week.",
    jobType: "Contract",
    remoteOptions: true,
    tags: ["Content Writing", "SEO", "Remote"],
  },
  {
    id: "13",
    title: "IT Support Specialist",
    company: "Tech Support Co.",
    location: "Columbus, OH",
    salary: "$50,000 - $65,000",
    level: "Entry-Level",
    description: "Provide technical support for users and systems.",
    requirements: [
      "Familiarity with Windows and Mac operating systems.",
      "Basic networking knowledge.",
      "Strong problem-solving skills.",
      "Good communication skills.",
    ],
    responsibilities: [
      "Respond to support tickets and resolve technical issues.",
      "Assist users with software and hardware problems.",
      "Document support processes and solutions.",
      "Install and configure computer systems.",
    ],
    additionalInfo: "Opportunities for career advancement.",
    companyWebsite: "https://techsupportco.com",
    benefits: [
      "Health benefits and retirement plans.",
      "Paid training and certifications.",
      "Flexible work schedule.",
    ],
    applicationDeadline: "2024-11-15",
    workHours: "Full-time, 40 hours per week.",
    jobType: "Permanent",
    remoteOptions: false,
    tags: ["IT Support", "Technical Support"],
  },
  {
    id: "14",
    title: "Sales Associate",
    company: "Retail World",
    location: "Phoenix, AZ",
    salary: "$30,000 - $40,000",
    level: "Entry-Level",
    description: "Drive sales and build client relationships.",
    requirements: [
      "Strong communication and interpersonal skills.",
      "Ability to work independently and as part of a team.",
      "Familiarity with CRM software is a plus.",
    ],
    responsibilities: [
      "Identify and pursue new business opportunities.",
      "Manage client accounts and ensure satisfaction.",
      "Meet sales targets and report progress.",
    ],
    additionalInfo: "Commission structure and bonuses available.",
    companyWebsite: "https://retailworld.com",
    benefits: [
      "Employee discounts and bonuses.",
      "Health and wellness programs.",
      "Flexible working hours.",
    ],
    applicationDeadline: "2024-12-01",
    workHours: "Part-time, 20-30 hours per week.",
    jobType: "Permanent",
    remoteOptions: false,
    tags: ["Sales", "Retail"],
  },
  {
    id: "15",
    title: "HR Specialist",
    company: "People Solutions",
    location: "Charlotte, NC",
    salary: "$55,000 - $70,000",
    level: "Mid-Level",
    description: "Manage HR functions and support employees.",
    requirements: [
      "Knowledge of labor laws and regulations.",
      "Strong communication and problem-solving skills.",
      "Experience with HR software is a plus.",
    ],
    responsibilities: [
      "Assist with recruitment and onboarding processes.",
      "Address employee inquiries and concerns.",
      "Maintain employee records and HR database.",
    ],
    additionalInfo: "Collaborative and supportive work environment.",
    companyWebsite: "https://peoplesolutions.com",
    benefits: [
      "Comprehensive health insurance.",
      "401(k) retirement plan.",
      "Paid time off and holidays.",
    ],
    applicationDeadline: "2024-11-25",
    workHours: "Full-time, 40 hours per week.",
    jobType: "Permanent",
    remoteOptions: false,
    tags: ["HR", "Human Resources"],
  },
  {
    id: "16",
    title: "Network Engineer",
    company: "Tech Solutions",
    location: "Phoenix, AZ",
    salary: "$80,000 - $95,000",
    level: "Mid-Level",
    description: "Design and implement network solutions.",
    requirements: [
      "Experience with network configuration and management.",
      "Knowledge of routing and switching protocols.",
      "Certifications like CCNA or CompTIA Network+ are a plus.",
    ],
    responsibilities: [
      "Monitor network performance and troubleshoot issues.",
      "Collaborate with IT teams to improve network security.",
      "Document network configurations and procedures.",
    ],
    additionalInfo: "Growth opportunities available within the company.",
    companyWebsite: "https://techsolutions.com",
    benefits: [
      "Health and dental insurance.",
      "Flexible working hours.",
      "Professional development and training.",
    ],
    applicationDeadline: "2024-10-30",
    workHours: "Full-time, 40 hours per week.",
    jobType: "Permanent",
    remoteOptions: true,
    tags: ["Networking", "IT", "Engineering"],
  },
  {
    id: "17",
    title: "Business Analyst",
    company: "Consulting Group",
    location: "Los Angeles, CA",
    salary: "$75,000 - $90,000",
    level: "Mid-Level",
    description: "Analyze business processes and provide solutions.",
    requirements: [
      "Experience in business analysis or project management.",
      "Strong analytical and problem-solving skills.",
      "Ability to communicate effectively with stakeholders.",
    ],
    responsibilities: [
      "Gather and document business requirements.",
      "Analyze data and provide insights.",
      "Collaborate with teams to implement solutions.",
    ],
    additionalInfo: "Opportunity to work on diverse projects.",
    companyWebsite: "https://consultinggroup.com",
    benefits: [
      "Comprehensive health benefits.",
      "401(k) retirement plan with matching.",
      "Paid vacation and sick leave.",
    ],
    applicationDeadline: "2024-11-10",
    workHours: "Full-time, 40 hours per week.",
    jobType: "Permanent",
    remoteOptions: true,
    tags: ["Business Analysis", "Consulting"],
  },
  {
    id: "18",
    title: "Quality Control Inspector",
    company: "Manufacturing Inc.",
    location: "Detroit, MI",
    salary: "$40,000 - $50,000",
    level: "Entry-Level",
    description: "Ensure product quality through inspections.",
    requirements: [
      "Attention to detail and problem-solving skills.",
      "Ability to read technical drawings.",
      "Basic understanding of quality standards.",
    ],
    responsibilities: [
      "Conduct inspections of raw materials and finished products.",
      "Document inspection results and report defects.",
      "Collaborate with production teams to ensure quality.",
    ],
    additionalInfo: "Training provided for new hires.",
    companyWebsite: "https://manufacturinginc.com",
    benefits: [
      "Health and dental insurance.",
      "401(k) retirement plan.",
      "Paid time off.",
    ],
    applicationDeadline: "2024-10-30",
    workHours: "Full-time, 40 hours per week.",
    jobType: "Permanent",
    remoteOptions: false,
    tags: ["Quality Control", "Manufacturing"],
  },
  {
    id: "19",
    title: "Research Scientist",
    company: "Bio Labs",
    location: "San Diego, CA",
    salary: "$85,000 - $100,000",
    level: "Senior",
    description: "Conduct research and analysis in biotechnology.",
    requirements: [
      "Ph.D. in a related field.",
      "Strong analytical and experimental skills.",
      "Ability to work independently and in teams.",
    ],
    responsibilities: [
      "Design and conduct experiments.",
      "Analyze and interpret data.",
      "Collaborate with cross-functional teams.",
    ],
    additionalInfo: "Opportunity to publish research findings.",
    companyWebsite: "https://biolabs.com",
    benefits: [
      "Comprehensive health insurance.",
      "401(k) with employer match.",
      "Professional development opportunities.",
    ],
    applicationDeadline: "2024-11-20",
    workHours: "Full-time, 40 hours per week.",
    jobType: "Permanent",
    remoteOptions: true,
    tags: ["Research", "Biotechnology"],
  },
  {
    id: "20",
    title: "Database Administrator",
    company: "Data Management Co.",
    location: "Atlanta, GA",
    salary: "$80,000 - $95,000",
    level: "Mid-Level",
    description: "Manage and maintain database systems.",
    requirements: [
      "Experience with SQL and database management.",
      "Knowledge of database design and architecture.",
      "Strong problem-solving skills.",
    ],
    responsibilities: [
      "Monitor database performance and optimize queries.",
      "Implement backup and recovery procedures.",
      "Collaborate with developers to ensure data integrity.",
    ],
    additionalInfo: "Opportunities for further training and certifications.",
    companyWebsite: "https://datamanagementco.com",
    benefits: [
      "Health insurance coverage.",
      "401(k) retirement plan.",
      "Flexible work hours.",
    ],
    applicationDeadline: "2024-12-05",
    workHours: "Full-time, 40 hours per week.",
    jobType: "Permanent",
    remoteOptions: false,
    tags: ["Database", "SQL", "IT"],
  },
  // Add these to your existing jobs array in jobData.js

  {
    id: "21",
    title: "SEO Specialist",
    company: "RankHigher",
    location: "Los Angeles, CA",
    salary: "$50,000 - $65,000",
    level: "Mid-Level",
    description: "Optimize our website to improve search engine rankings.",
    requirements: [
      "2+ years of experience in SEO.",
      "Knowledge of Google Analytics and SEO tools.",
      "Strong analytical skills.",
    ],
    responsibilities: [
      "Conduct keyword research.",
      "Analyze website performance.",
      "Implement on-page and off-page SEO strategies.",
    ],
    additionalInfo: "Opportunity for growth into a managerial role.",
    companyWebsite: "https://rankhigher.com",
    benefits: [
      "Health insurance.",
      "Flexible working hours.",
      "Remote work options.",
    ],
    applicationDeadline: "2024-11-15",
    workHours: "Full-time, 40 hours per week.",
    jobType: "Permanent",
    remoteOptions: true,
    tags: ["SEO", "Marketing", "Analytics"],
  },
  {
    id: "22",
    title: "Graphic Designer",
    company: "Creative Minds",
    location: "Austin, TX",
    salary: "$45,000 - $55,000",
    level: "Entry-Level",
    description: "Design engaging graphics for various media.",
    requirements: [
      "Proficiency in Adobe Creative Suite.",
      "Strong portfolio of design work.",
      "Creativity and attention to detail.",
    ],
    responsibilities: [
      "Create visuals for digital marketing campaigns.",
      "Collaborate with the marketing team.",
      "Ensure brand consistency in designs.",
    ],
    additionalInfo: "Flexible work schedule and creative freedom.",
    companyWebsite: "https://creativeminds.com",
    benefits: [
      "Professional development opportunities.",
      "Paid time off.",
      "Team-building events.",
    ],
    applicationDeadline: "2024-11-30",
    workHours: "Full-time, 40 hours per week.",
    jobType: "Contract",
    remoteOptions: true,
    tags: ["Design", "Adobe", "Creativity"],
  },
  {
    id: "23",
    title: "Data Analyst",
    company: "Data Insights",
    location: "Chicago, IL",
    salary: "$70,000 - $80,000",
    level: "Mid-Level",
    description: "Analyze and interpret complex data sets.",
    requirements: [
      "Experience with SQL and data visualization tools.",
      "Strong analytical skills.",
      "Bachelor's degree in a related field.",
    ],
    responsibilities: [
      "Create reports and dashboards.",
      "Identify trends and insights.",
      "Collaborate with stakeholders.",
    ],
    additionalInfo: "Opportunities for certifications in data analysis.",
    companyWebsite: "https://datainsights.com",
    benefits: [
      "Retirement plan with employer match.",
      "Health and wellness programs.",
      "Work-life balance initiatives.",
    ],
    applicationDeadline: "2024-12-01",
    workHours: "Full-time, 40 hours per week.",
    jobType: "Permanent",
    remoteOptions: false,
    tags: ["Data", "Analysis", "SQL"],
  },
  {
    id: "24",
    title: "Content Writer",
    company: "WriteWell",
    location: "Remote",
    salary: "$40,000 - $55,000",
    level: "Entry-Level",
    description: "Create engaging content for blogs and websites.",
    requirements: [
      "Strong writing and editing skills.",
      "Familiarity with SEO best practices.",
      "Ability to work independently.",
    ],
    responsibilities: [
      "Research and write articles.",
      "Edit content for clarity and quality.",
      "Collaborate with the marketing team.",
    ],
    additionalInfo: "Potential for long-term contracts.",
    companyWebsite: "https://writewell.com",
    benefits: [
      "Flexible schedule.",
      "Work from home.",
      "Continuous learning opportunities.",
    ],
    applicationDeadline: "2024-11-20",
    workHours: "Part-time, 20 hours per week.",
    jobType: "Freelance",
    remoteOptions: true,
    tags: ["Writing", "Content", "SEO"],
  },
  {
    id: "25",
    title: "Product Manager",
    company: "Innovate Tech",
    location: "Seattle, WA",
    salary: "$90,000 - $110,000",
    level: "Senior-Level",
    description: "Lead product development from concept to launch.",
    requirements: [
      "5+ years of experience in product management.",
      "Strong understanding of Agile methodologies.",
      "Excellent communication skills.",
    ],
    responsibilities: [
      "Define product vision and strategy.",
      "Conduct market research.",
      "Collaborate with cross-functional teams.",
    ],
    additionalInfo: "Opportunities for leadership training.",
    companyWebsite: "https://innovatetech.com",
    benefits: [
      "Stock options.",
      "Health insurance.",
      "Professional development budget.",
    ],
    applicationDeadline: "2024-12-10",
    workHours: "Full-time, 40 hours per week.",
    jobType: "Permanent",
    remoteOptions: false,
    tags: ["Product", "Management", "Agile"],
  },
  {
    id: "26",
    title: "Full Stack Developer",
    company: "CodeCrafters",
    location: "Boston, MA",
    salary: "$80,000 - $100,000",
    level: "Mid-Level",
    description:
      "Build and maintain web applications using full-stack technologies.",
    requirements: [
      "Proficiency in JavaScript, HTML, and CSS.",
      "Experience with Node.js and React.",
      "Strong problem-solving skills.",
    ],
    responsibilities: [
      "Develop front-end and back-end applications.",
      "Optimize applications for maximum speed.",
      "Collaborate with designers and product managers.",
    ],
    additionalInfo: "Work on cutting-edge technologies.",
    companyWebsite: "https://codecrafters.com",
    benefits: [
      "Health and dental insurance.",
      "Flexible working environment.",
      "Team retreats.",
    ],
    applicationDeadline: "2024-12-15",
    workHours: "Full-time, 40 hours per week.",
    jobType: "Permanent",
    remoteOptions: true,
    tags: ["Development", "Full Stack", "JavaScript"],
  },
  {
    id: "27",
    title: "DevOps Engineer",
    company: "Cloud Solutions",
    location: "Denver, CO",
    salary: "$95,000 - $115,000",
    level: "Senior-Level",
    description: "Automate and streamline operations and processes.",
    requirements: [
      "3+ years of experience in DevOps.",
      "Knowledge of CI/CD tools and cloud services.",
      "Strong scripting skills.",
    ],
    responsibilities: [
      "Implement automation tools and frameworks.",
      "Monitor system performance.",
      "Collaborate with development teams.",
    ],
    additionalInfo: "Opportunities for certifications in DevOps.",
    companyWebsite: "https://cloudsolutions.com",
    benefits: [
      "Generous PTO policy.",
      "Professional growth opportunities.",
      "Health and wellness programs.",
    ],
    applicationDeadline: "2024-11-25",
    workHours: "Full-time, 40 hours per week.",
    jobType: "Permanent",
    remoteOptions: true,
    tags: ["DevOps", "Cloud", "Automation"],
  },
  {
    id: "28",
    title: "Marketing Manager",
    company: "Brand Builders",
    location: "Miami, FL",
    salary: "$70,000 - $85,000",
    level: "Mid-Level",
    description: "Develop and execute marketing strategies.",
    requirements: [
      "4+ years of marketing experience.",
      "Strong analytical and project management skills.",
      "Proficiency in marketing tools.",
    ],
    responsibilities: [
      "Create and manage marketing campaigns.",
      "Analyze campaign performance.",
      "Lead the marketing team.",
    ],
    additionalInfo: "Opportunity to lead major marketing initiatives.",
    companyWebsite: "https://brandbuilders.com",
    benefits: ["401(k) plan.", "Health insurance.", "Paid parental leave."],
    applicationDeadline: "2024-12-12",
    workHours: "Full-time, 40 hours per week.",
    jobType: "Permanent",
    remoteOptions: false,
    tags: ["Marketing", "Management", "Strategy"],
  },
  {
    id: "29",
    title: "Business Analyst",
    company: "Consulting Group",
    location: "Atlanta, GA",
    salary: "$65,000 - $80,000",
    level: "Mid-Level",
    description: "Analyze business processes and provide recommendations.",
    requirements: [
      "Strong analytical and problem-solving skills.",
      "Experience with data analysis tools.",
      "Bachelor's degree in Business or related field.",
    ],
    responsibilities: [
      "Conduct business analysis.",
      "Create detailed documentation.",
      "Collaborate with stakeholders.",
    ],
    additionalInfo: "Potential for career advancement within the company.",
    companyWebsite: "https://consultinggroup.com",
    benefits: [
      "Comprehensive health benefits.",
      "Flexible work hours.",
      "Company-sponsored training.",
    ],
    applicationDeadline: "2024-11-28",
    workHours: "Full-time, 40 hours per week.",
    jobType: "Permanent",
    remoteOptions: false,
    tags: ["Business", "Analysis", "Consulting"],
  },
  {
    id: "30",
    title: "UI/UX Designer",
    company: "Design Hub",
    location: "Portland, OR",
    salary: "$65,000 - $75,000",
    level: "Mid-Level",
    description: "Design user-friendly interfaces and experiences.",
    requirements: [
      "Experience with design tools (Figma, Sketch).",
      "Strong portfolio showcasing design work.",
      "Knowledge of user-centered design principles.",
    ],
    responsibilities: [
      "Conduct user research and usability testing.",
      "Create wireframes and prototypes.",
      "Collaborate with developers and product teams.",
    ],
    additionalInfo: "Work in a creative and dynamic environment.",
    companyWebsite: "https://designhub.com",
    benefits: [
      "Remote work options.",
      "Health insurance.",
      "Creative work environment.",
    ],
    applicationDeadline: "2024-11-22",
    workHours: "Full-time, 40 hours per week.",
    jobType: "Permanent",
    remoteOptions: true,
    tags: ["UI/UX", "Design", "User Experience"],
  },
];

export default jobs;
